trainer: ocp

dataset:
  train:
    src: datasets/mptrj-gga-ggapu/mptrj-gga-ggapu
    type: "train"
  val:
    src: datasets/mptrj-gga-ggapu/mptrj-gga-ggapu
    type: "val"

logger: wandb

outputs:
  energy:
    shape: 1
    level: system
  forces:
    irrep_dim: 1
    level: atom
    train_on_free_atoms: True
    eval_on_free_atoms: True

loss_functions:
  - energy:
      fn: mae
      coefficient: 4
  - forces:
      fn: l2mae
      coefficient: 100

evaluation_metrics:
  metrics:
    energy:
      - mae
      - mse
      - energy_within_threshold
    forces:
      - mae
      - cosine_similarity
      - magnitude_error
    misc:
      - energy_forces_within_threshold
  primary_metric: forces_mae

task:
  relaxation_steps: 125
  relaxation_fmax: 0.05
  write_pos: True
  relax_dataset:
    src: data_odac/is2r/val
  relax_opt:
    name: lbfgs
    maxstep: 0.04
    memory: 50
    damping: 1.0
    alpha: 70.0
